### ISSUE TITLE
Prominently document that anchors are calculated like on GitHub

### ISSUE THREAD

**Issue by not-my-profile** [rossmacarthur/pulldown-cmark-toc#3]
This is currently only documented on the `Heading::anchor` method:

https://github.com/rossmacarthur/pulldown-cmark-toc/blob/9ac711fd37c271fb0f61be839a161dbb43dbb98b/src/lib.rs#L82-L87

I think it should be more prominently documented (i.e. mentioned in both the README as well as the doc comment for the root module), since this is an important detail.

Sidenote: How do we know that GitHub uses this anchor calculation? Is it documented somewhere? Have you come up with this function yourself or taken it from elsewhere? (This should probably noted in a code comment.)

**Comment by rossmacarthur** [comment]
Unfortunately GitHub doesn't seem to document this behaviour. I suspect it has also changed since I implemented this and might need an update. I think I previously copied the behaviour from this VS Code extension :

https://github.com/yzhang-gh/vscode-markdown/blob/83f602638bf96f5249e3b9856baf9f31b933fad1/src/util/slugify.ts#L92

**Comment by not-my-profile** [comment]
Yes I agree that it's unfortunate. I think this really ought to be part of the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/) ... which doesn't mention anchor or slug at all. Unfortunately the spec does not appear to be in a public repository so I cannot open an issue with the spec that it should cover this.

I looked into this a bit and the most popular solution seems to be the [github-slugger NPM package](https://www.npmjs.com/package/github-slugger), for which there also exists [a Rust port](https://crates.io/crates/github-slugger). However looking at their code they use a [much more complicated Regex](https://github.com/chrisjsewell/markdown-it-plugins.rs/blob/bfc1c6f584b44b14e8e6ae0371768276d04e0d7b/crates/github_slugger/src/lib.rs#L14-L17) and I tested their fixtures.json against the anchor function of this repository and all the tests passed except the [Format test](https://github.com/chrisjsewell/markdown-it-plugins.rs/blob/main/crates/github_slugger/tests/fixtures.json#L271-L275) which contains some Unicode gibberish, I personally wouldn't worry about.
